// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehndglybcayryosyipet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVobmRnbHliY2F5cnlvc3lpcGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTQ3NzksImV4cCI6MjA3NDUzMDc3OX0.4qTutc0kQxF3VAVmAUXRBSbWbbbQH9MyJU1QLBnL4U8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});